version: '3.4'

services:
 database:
   image: "mcr.microsoft.com/mssql/server:2017-latest"
   container_name: dev_cadempresafuncionario_sql
   environment:
     SA_PASSWORD : admin*123
     ACCEPT_EULA: "Y"
   ports:
    - "1433:1433"

 cadempresafornecedor.api:
   image: ${DOCKER_REGISTRY-}cadempresafornecedorapi
   ports:
     - 5001:443
     - 5000:80
   build:
     context: .
     dockerfile: CadEmpresaFornecedor.Api/Dockerfile
   environment:
    - SEED=true
    - 'ConnectionStrings__DbConn=Data Source=database;Initial Catalog=CadEmpresaFornecedorApi;User Id=sa;Password=admin*123' 
   depends_on:
     - database
